config/routes.rb
Rails.application.routes.draw do
  post 'uploader/image'
  devise_for :users
  root to: "pages#home"
  resources :articles
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :article_keywords
  has_many :keywords, through: :article_keywords
  # un article doit toujours être associé à un utilisateur lors de sa création ou de sa mise à jour:
  validates :user, presence: true
  # Un article doit avoir un titre
  validates :title, presence: true, length: { minimum: 5 }
  # Ajout activeStorage aux articles pour pouvoir faciliter
  # has_many_attached :images, service: :local, dependent: :purge
  has_many_attached :images, dependent: :purge
  # Ajout de pièces jointes aux article
  has_many_attached :documents, dependent: :purge_later
  has_many :comments, dependent: :destroy
  has_many :article_tags
  has_many :tags, through: :article_tags
  # Association 'likes' fusionnée avec les options nécessaires
  has_many :likes, dependent: :destroy, counter_cache: true
  has_many :liking_users, through: :likes, source: :user
end

app/models/article_keyword.rb
class ArticleKeyword < ApplicationRecord
  belongs_to :article
  belongs_to :keyword
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  validates :nom, presence: true
	  validates :image, presence: true
	  has_many :articles
	  has_one_attached :image
	  # Ajout de l'attribut pour la couleur de fond
  attribute :background_color, :string
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  # Valide que le contenu est présent
  validates :content, presence: { message: :empty }
  # Valide que le contenu a une longueur minimale de 10 caractères
  validates :content, length: { minimum: 8, message: :too_short }
# :empty et :too_short sont des symboles qui correspondent à des clés de localisation.
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :article_keywords
  has_many :articles, through: :article_keywords
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
  # Ajout photo a l'utilisateur
  has_one_attached :photo
  has_many :articles
  has_many :comments
  # Partie J'aime
  has_many :likes, dependent: :destroy # Quand on supprime un user, likes seront supprimés
  has_many :liked_articles, through: :likes, source: :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :destroy, :update]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @user = current_user # Pour que le header puisse s'afficher avec le login
    @categories = Category.all
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to  article_path(@article), notice: 'Article créé!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: "Article mis à jour."
    else
      render :edit, alert: "Impossible de mettre à jour l\'article."
    end
  end

  def destroy
    # On récupère l'id avec before_action
    # On supprime l'enregistrement avec l'id dans la BdD
    @article.destroy
    # On redirige vers la page index
    redirect_to articles_path, status: :see_other, :notice => "Article supprimé!"
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def set_article
    @article = Article.find(params[:id])
    @user = current_user # Pour que le header puisse s'afficher avec le login
    @categories = Category.all
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_id, images: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to  category_path(@category), notice: 'Categorie créée!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Catégorie a été mis à jour."
    else
      render :edit, alert: "Impossible de mettre à jour la catégorie."
    end
  end

  def destroy
    # On récupère l'id avec before_action
    # On supprime l'enregistrement avec l'id dans la BdD
    @category.destroy
    # On redirige vers la page index
    redirect_to categories_path, status: :see_other, :notice => "Catégorie supprimée!"
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:nom, :image, :background_color)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  skip_before_action :verify_authenticity_token
  def image
    blob = ActiveStorage::Blob.create_and_upload!(
      io:           params[:file],
      filename:     params[:file].original_filename,
      content_type: params[:file].content_type
    )

    render json: {location: url_for(blob)}, content_type: "text/html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>
<div class="container">
  <h1>Création d'un article</h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.error_notification %>
    <%= f.input :title, label: "Titre" %>
    <%= f.input :category_id,
                      required: true,
                      autofocus: true,
                      collection: @categories,
                      label_method: :nom,
                      value_method: :id,
                      include_blank: 'Sélectionnez une catégorie',
                      label: "Catégories" %>
    <%= f.label :content, 'Contenu' %>
    <%= f.text_area :content, class: "tinymce", rows: 30, style: 'width: 100%' %>
    <%= tinymce :default %>
    <% if @article.images.attached? %>
      Images actuelles : <br>
      <% @article.images.each do |image| %>
            <%= image_tag image %>
          <% end %>
    <% end %>
    <%= f.input :images,
                      as: :file,
                      label: "Choisir des images",
                      input_html: {
                        multiple: true
                      }
          %>
    <%= f.button :submit, "Modifier", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Liste des articles</h1>
  <%# Lien vers la vue new pour créer un article %>
  <p><%= link_to "Créer", new_article_path %></p>
  <div class="row">
    <table class="table liste-articles table-striped table-bordered">
      <th>Nom</th>
      <th>Détail</th>
      <th>Modifier</th>
      <th>Supprimer</th>
      <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td>
        <%# Lien vers la vue show pour voir le détail d'un article %>
          <%= link_to "Voir", article_path(article) %>
        </td>
        <td>
        <%# Lien vers la vue edit pour modifier un article %>
          <%= link_to "Modifier", edit_article_path(article) %>
        </td>
        <td>
        <%# Lien pour supprimer un article %>
          <%= link_to article_path(article),
            data: {turbo_method: :delete, turbo_confirm: "Etes vous sure ?", :method=>'delete'} do %>
            <i class="fa-solid fa-trash-can me-3 text-danger"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Création d'un article</h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.error_notification %>
    <%= f.input :title, label: "Titre" %>
    <%= f.input :category_id,
                      required: true,
                      autofocus: true,
                      collection: @categories,
                      label_method: :nom,
                      value_method: :id,
                      include_blank: 'Sélectionnez une catégorie',
                      label: "Catégories" %>
    <%= f.label :content, 'Contenu' %>
    <%= f.text_area :content, class: "tinymce", rows: 30, style: 'width: 100%' %>
    <%= tinymce :default %>

    <%= f.input :images,
                      as: :file,
                      label: "Choisir des images",
                      input_html: {
                        multiple: true
                      }
          %>
    <%= f.button :submit, "Créer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <h1>Articles#show</h1>
    <p>Find me in app/views/articles/show.html.erb</p>
    <div class="card">
      <div class="article-title">
        Titre : <%= @article.title %>
      </div>
      <div class="article-category">
        Catégorie : <%= @article.category.nom %>
      </div>
      <div class="article-image">
        <% if @article.images.attached? %>
          <% @article.images.each do |image| %>
            <%= image_tag image %>
          <% end %>
        <% end %>
      </div>
      <div class="article-content">
        Contenu : <%= raw @article.content %>
      </div>

    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Modification d'une catégorie</h1>
  <%= simple_form_for(@category) do |f| %>
    <%= f.input :nom %>

    <% if @category.image.attached? %>
      <p>Image actuelle :</p>
      <%= image_tag @category.image %>
    <% end %>

    <%= f.input :image, as: :file, label: "Choisir une image" %>
    <%= f.input :background_color, as: :color, label: "Couleur de fond", input_html: { style: 'width: 100px;' } %>
    <%= f.button :submit, "Mettre à jour", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1>Liste des catégories</h1>
  <%# Lien vers la vue new pour créer une catégorie %>
  <p><%= link_to "Créer", new_category_path %></p>
  <div class="row">
    <table class="table liste-categories table-striped table-bordered">
      <th>Nom</th>
      <th>Détail</th>
      <th>Modifier</th>
      <th>Supprimer</th>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.nom %></td>
        <td>
        <%# Lien vers la vue show pour voir le détail d'une catégorie %>
          <%= link_to "Voir", category_path(category) %>
        </td>
        <td>
        <%# Lien vers la vue edit pour modifier une catégorie %>
          <%= link_to "Modifier", edit_category_path(category) %>
        </td>
        <td>
        <%# Lien pour supprimer une catégorie %>
          <%= link_to category_path(category),
            data: {turbo_method: :delete, turbo_confirm: "Etes vous sure ?", :method=>'delete'} do %>
            <i class="fa-solid fa-trash-can me-3 text-danger"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>Ajout d'une catégorie</h1>
  <%= simple_form_for(@category) do |f| %>
    <%= f.input :nom %>
    <%= f.input :image, as: :file, label: "Choisir une image" %>
    <%= f.input :background_color, as: :color, label: "Couleur de fond", input_html: { style: 'width: 100px;' } %>
    <%= f.button :submit, "Créer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <h1><%= @category.nom %></h1>
    <p>Image :
      <% if @category.image.attached? %>
        <%= image_tag @category.image %>
      <% end %>
    </p>
    <p>
      Couleur : <%= @category.background_color %>
    </p>
    <%= link_to "Retour", categories_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntranetCms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= tinymce_assets %>
    <meta name="turbo-cache-control" content="no-cache">
    <meta name="turbo-visit-control" content="reload">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/uploader/image.html.erb
<h1>Uploader#image</h1>
<p>Find me in app/views/uploader/image.html.erb</p>